#!/usr/bin/env python3
"""
error_analysis.py

This script performs error analysis on result JSON files generated by any of the approaches.
It uses the shared analyze_errors() function from factchecker_base.
"""

import os
import argparse
import logging

from factchecker_base import analyze_errors

def main():
    parser = argparse.ArgumentParser(description="Run Error Analysis on a Result JSON File")
    parser.add_argument("--result_file", type=str, required=True, help="Path to the result JSON file")
    args = parser.parse_args()
    analyze_errors(args.result_file)

if __name__ == "__main__":
    main()
